ReversiForm: ReversiForm.SettingForm Class Reference
ReversiForm.SettingForm Class Reference
SettingFormクラス
Public Member Functions
SettingForm (ReversiSetting mSetting)
コンストラクタ
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
ReversiSetting mSetting [get, set]
Private Member Functions
void reflectSettingForm ()
フォームに設定を反映
void loadSettingForm ()
void pictureBoxPlayerColor1_Click (object sender, EventArgs e)
プレイヤー1の色クリック
void pictureBoxPlayerColor2_Click (object sender, EventArgs e)
void pictureBoxBackGroundColor_Click (object sender, EventArgs e)
void pictureBoxBorderColor_Click (object sender, EventArgs e)
void buttonDefault_Click (object sender, EventArgs e)
void buttonSave_Click (object sender, EventArgs e)
保存ボタンクリック
void buttonCancel_Click (object sender, EventArgs e)
プレイヤー2の色クリック
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ReversiSetting _mSetting
リバーシ設定クラス
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBoxMode
System.Windows.Forms.RadioButton radioButtonMode2
System.Windows.Forms.RadioButton radioButtonMode1
System.Windows.Forms.RadioButton radioButtonType2
System.Windows.Forms.GroupBox groupBoxType
System.Windows.Forms.RadioButton radioButtonType3
System.Windows.Forms.RadioButton radioButtonType1
System.Windows.Forms.RadioButton radioButtonPlayer2
System.Windows.Forms.RadioButton radioButtonPlayer1
System.Windows.Forms.GroupBox groupBoxPlayer
System.Windows.Forms.RadioButton radioButtonAssist2
System.Windows.Forms.RadioButton radioButtonAssist1
System.Windows.Forms.GroupBox groupBoxAssist
System.Windows.Forms.RadioButton radioButtonGameSpd3
System.Windows.Forms.RadioButton radioButtonGameSpd2
System.Windows.Forms.RadioButton radioButtonGameSpd1
System.Windows.Forms.GroupBox groupBoxGameSpd
System.Windows.Forms.RadioButton radioButtonEndAnim2
System.Windows.Forms.RadioButton radioButtonEndAnim1
System.Windows.Forms.GroupBox groupBoxEndAnim
System.Windows.Forms.GroupBox groupBoxMasuCntMenu
System.Windows.Forms.RadioButton radioButtonMasuCntMenu8
System.Windows.Forms.RadioButton radioButtonMasuCntMenu7
System.Windows.Forms.RadioButton radioButtonMasuCntMenu6
System.Windows.Forms.RadioButton radioButtonMasuCntMenu3
System.Windows.Forms.RadioButton radioButtonMasuCntMenu5
System.Windows.Forms.RadioButton radioButtonMasuCntMenu2
System.Windows.Forms.RadioButton radioButtonMasuCntMenu4
System.Windows.Forms.RadioButton radioButtonMasuCntMenu1
System.Windows.Forms.PictureBox pictureBoxPlayerColor1
System.Windows.Forms.Label labelPlayerColor1
System.Windows.Forms.Label labelPlayerColor2
System.Windows.Forms.PictureBox pictureBoxPlayerColor2
System.Windows.Forms.Label labelBackGroundColor
System.Windows.Forms.PictureBox pictureBoxBackGroundColor
System.Windows.Forms.Label labelBorderColor
System.Windows.Forms.PictureBox pictureBoxBorderColor
System.Windows.Forms.Button buttonSave
System.Windows.Forms.Button buttonCancel
System.Windows.Forms.Button buttonDefault
Detailed Description
SettingFormクラス
Definition at line 35 of file SettingForm.cs.
Constructor & Destructor Documentation
SettingForm()
ReversiForm.SettingForm.SettingForm (ReversiSetting mSetting)
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 57 of file SettingForm.cs.
Member Function Documentation
buttonCancel_Click()
void ReversiForm.SettingForm.buttonCancel_Click (object sender, EventArgs e) private
プレイヤー2の色クリック
キャンセルボタンクリック
デフォルト設定に戻すボタンクリック
枠線の色クリック
背景の色クリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 466 of file SettingForm.cs.
Referenced by ReversiForm.SettingForm.InitializeComponent().
buttonSave_Click()
void ReversiForm.SettingForm.buttonSave_Click (object sender, EventArgs e) private
保存ボタンクリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 450 of file SettingForm.cs.
Referenced by ReversiForm.SettingForm.InitializeComponent().
Dispose()
override void ReversiForm.SettingForm.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file SettingForm.Designer.cs.
Referenced by ReversiForm.Reversi.button2_Click().
InitializeComponent()
void ReversiForm.SettingForm.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file SettingForm.Designer.cs.
Referenced by ReversiForm.SettingForm.SettingForm().
pictureBoxPlayerColor1_Click()
void ReversiForm.SettingForm.pictureBoxPlayerColor1_Click (object sender, EventArgs e) private
プレイヤー1の色クリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 338 of file SettingForm.cs.
Referenced by ReversiForm.SettingForm.InitializeComponent().
reflectSettingForm()
void ReversiForm.SettingForm.reflectSettingForm () private
フォームに設定を反映
フォームから設定を読み込み
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 72 of file SettingForm.cs.
Referenced by ReversiForm.SettingForm.pictureBoxPlayerColor1_Click(), and ReversiForm.SettingForm.SettingForm().
Member Data Documentation
components
System.ComponentModel.IContainer ReversiForm.SettingForm.components = null private
Required designer variable.
Definition at line 8 of file SettingForm.Designer.cs.
Referenced by ReversiForm.SettingForm.Dispose().
The documentation for this class was generated from the following files:
SettingForm.cs
SettingForm.Designer.cs