ReversiForm: ReversiForm.ReversiPlay Class Reference
ReversiForm.ReversiPlay Class Reference
リバーシプレイクラス
Public Member Functions
delegate void ViewMsgDlg (string title, string msg)
delegate void DrawSingle (int y, int x, int sts, int bk, string text)
delegate void CurColMsg (string text)
delegate void CurStsMsg (string text)
ReversiPlay ()
コンストラクタ
ReversiPlay Clone ()
コピー
void reversiPlay (int y, int x)
リバーシプレイ
void reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
void reversiPlayEnd ()
リバーシプレイ終了
void reversiPlayPass (int color)
リバーシプレイパス
int reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
void drawUpdate (int assist)
マス描画更新
void drawUpdateForcibly (int assist)
マス描画強制更新
void reset ()
リセット処理
int gameEndAnimExec ()
ゲーム終了アニメーション
void sendDrawMsg (int y, int x)
描画メッセージ送信
void sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Properties
MyReversi mReversi [get, set]
ReversiSetting mSetting [get, set]
int mCurColor [get, set]
ReversiPoint [] mCpu [get, set]
ReversiPoint [] mEdge [get, set]
int mPassEnaB [get, set]
int mPassEnaW [get, set]
int mGameEndSts [get, set]
int mPlayLock [get, set]
ViewMsgDlg viewMsgDlg [get, set]
DrawSingle drawSingle [get, set]
CurColMsg curColMsg [get, set]
CurStsMsg curStsMsg [get, set]
Private Member Functions
void execMessage (int what, Object obj)
メッセージ
void ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
void DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
void CurColMsgLocal (string text)
現在の色メッセージ
void CurStsMsgLocal (string text)
現在のステータスメッセージ
Private Attributes
MyReversi _mReversi
リバーシクラス
ReversiSetting _mSetting
リバーシ設定クラス
int _mCurColor = 0
現在の色
ReversiPoint [] _mCpu
CPU用ワーク
ReversiPoint [] _mEdge
CPU用角マスワーク
int _mPassEnaB = 0
黒のパス有効フラグ
int _mPassEnaW = 0
白のパス有効フラグ
int _mGameEndSts = 0
ゲーム終了ステータス
int _mPlayLock = 0
プレイロック
ViewMsgDlg _viewMsgDlg = null
メッセージコールバック
DrawSingle _drawSingle = null
描画コールバック
CurColMsg _curColMsg = null
現在の色メッセージコールバック
CurStsMsg _curStsMsg = null
現在のステータスメッセージコールバック
System.Random r = new System.Random()
乱数
Detailed Description
リバーシプレイクラス
Definition at line 30 of file ReversiPlay.cs.
Constructor & Destructor Documentation
ReversiPlay()
ReversiForm.ReversiPlay.ReversiPlay ()
コンストラクタ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 132 of file ReversiPlay.cs.
Member Function Documentation
Clone()
ReversiPlay ReversiForm.ReversiPlay.Clone ()
コピー
Returns
オブジェクトコピー
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 152 of file ReversiPlay.cs.
CurColMsgLocal()
void ReversiForm.ReversiPlay.CurColMsgLocal (string text) private
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 962 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.execMessage().
CurStsMsgLocal()
void ReversiForm.ReversiPlay.CurStsMsgLocal (string text) private
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 976 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.execMessage().
DrawSingleLocal()
void ReversiForm.ReversiPlay.DrawSingleLocal (int y, int x, int sts, int bk, string text) private
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 948 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.execMessage().
drawUpdate()
void ReversiForm.ReversiPlay.drawUpdate (int assist)
マス描画更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 620 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlay(), and ReversiForm.ReversiPlay.reversiPlayCpu().
drawUpdateForcibly()
void ReversiForm.ReversiPlay.drawUpdateForcibly (int assist)
マス描画強制更新
Parameters
[in] int assist アシスト設定
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 653 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reset(), and ReversiForm.Reversi.Reversi_Resize().
execMessage()
void ReversiForm.ReversiPlay.execMessage (int what, Object obj) private
メッセージ
Parameters
[in] int what
[in] var obj
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 835 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.drawUpdate(), ReversiForm.ReversiPlay.drawUpdateForcibly(), ReversiForm.ReversiPlay.gameEndAnimExec(), ReversiForm.ReversiPlay.reset(), ReversiForm.ReversiPlay.reversiPlay(), ReversiForm.ReversiPlay.reversiPlayCpu(), ReversiForm.ReversiPlay.reversiPlayEnd(), ReversiForm.ReversiPlay.sendDrawInfoMsg(), and ReversiForm.ReversiPlay.sendDrawMsg().
gameEndAnimExec()
int ReversiForm.ReversiPlay.gameEndAnimExec ()
ゲーム終了アニメーション
Returns
ウェイト時間
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 728 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlayEnd().
reset()
void ReversiForm.ReversiPlay.reset ()
リセット処理
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 678 of file ReversiPlay.cs.
Referenced by ReversiForm.Reversi.button1_Click(), and ReversiForm.Reversi.button2_Click().
reversiPlay()
void ReversiForm.ReversiPlay.reversiPlay (int y, int x)
リバーシプレイ
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 167 of file ReversiPlay.cs.
Referenced by ReversiForm.Reversi.pictureBox_Click().
reversiPlayCpu()
int ReversiForm.ReversiPlay.reversiPlayCpu (int color, int cpuEna)
リバーシプレイコンピューター
Parameters
[in] int color CPU色
[in] int cpuEna CPU有効フラグ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 361 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlaySub().
reversiPlayEnd()
void ReversiForm.ReversiPlay.reversiPlayEnd ()
リバーシプレイ終了
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 291 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlay(), and ReversiForm.ReversiPlay.reversiPlaySub().
reversiPlayPass()
void ReversiForm.ReversiPlay.reversiPlayPass (int color)
リバーシプレイパス
Parameters
[in] int color パス色
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 339 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlay(), and ReversiForm.ReversiPlay.reversiPlaySub().
reversiPlaySub()
void ReversiForm.ReversiPlay.reversiPlaySub (int cpuEna, int tmpCol)
リバーシプレイサブ
Parameters
[in] int cpuEna
[in] int tmpCol
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 261 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlay().
sendDrawInfoMsg()
void ReversiForm.ReversiPlay.sendDrawInfoMsg (int y, int x)
情報描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 816 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.drawUpdate().
sendDrawMsg()
void ReversiForm.ReversiPlay.sendDrawMsg (int y, int x)
描画メッセージ送信
Parameters
[in] int y Y座標
[in] int x X座標
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 797 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.drawUpdate(), ReversiForm.ReversiPlay.gameEndAnimExec(), ReversiForm.ReversiPlay.reversiPlay(), and ReversiForm.ReversiPlay.reversiPlayCpu().
ViewMsgDlgLocal()
void ReversiForm.ReversiPlay.ViewMsgDlgLocal (string title, string msg) private
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 930 of file ReversiPlay.cs.
Referenced by ReversiForm.ReversiPlay.reversiPlay(), ReversiForm.ReversiPlay.reversiPlayEnd(), and ReversiForm.ReversiPlay.reversiPlayPass().
The documentation for this class was generated from the following file:
Model/ReversiPlay.cs