ReversiForm: ReversiForm.Reversi Class Reference
ReversiForm.Reversi Class Reference
Public Member Functions
ReversiSetting LoadSettingXml (string path)
設定XMLファイルロード
int SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
void appInit ()
アプリ初期化
void ViewMsgDlg (string title, string msg)
メッセージダイアログ
void ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
void DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
void DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
void CurColMsg (string text)
現在の色メッセージ
void CurColMsgLocal (string text)
現在の色メッセージ
void CurStsMsg (string text)
現在のステータスメッセージ
void CurStsMsgLocal (string text)
現在のステータスメッセージ
Public Attributes
ReversiSetting m_AppSettings
アプリ設定
ReversiPlay m_ReversiPlay
リバーシ本体
Protected Member Functions
override void Dispose (bool disposing)
使用中のリソースをすべてクリーンアップします。
Private Member Functions
delegate void ViewMsgDlgDelegate (string title, string msg)
delegate void DrawSingleDelegate (int y, int x, int sts, int bk, string text)
delegate void CurColMsgDelegate (string text)
delegate void CurStsMsgDelegate (string text)
delegate void Reversi_ResizeEndDelegate (object sender, EventArgs e)
void pictureBox_Click (object sender, EventArgs e)
マスクリック
void button1_Click (object sender, EventArgs e)
リセットクリック
void button2_Click (object sender, EventArgs e)
セッティングクリック
void Reversi_Resize (object sender, EventArgs e)
リサイズイベント
void Reversi_ResizeEnd (object sender, EventArgs e)
void OnTimedEvent (object source, ElapsedEventArgs e)
タイマーイベント
void InitializeComponent ()
デザイナー サポートに必要なメソッドです。このメソッドの内容を コード エディターで変更しないでください。
Private Attributes
Size oldSize
リサイズ前のサイズ
System.ComponentModel.IContainer components = null
必要なデザイナー変数です。
System.Windows.Forms.TableLayoutPanel tableLayoutPanel1
System.Windows.Forms.PictureBox pictureBox381
System.Windows.Forms.PictureBox pictureBox382
System.Windows.Forms.PictureBox pictureBox383
System.Windows.Forms.PictureBox pictureBox384
System.Windows.Forms.PictureBox pictureBox385
System.Windows.Forms.PictureBox pictureBox386
System.Windows.Forms.PictureBox pictureBox387
System.Windows.Forms.PictureBox pictureBox388
System.Windows.Forms.PictureBox pictureBox389
System.Windows.Forms.PictureBox pictureBox390
System.Windows.Forms.PictureBox pictureBox391
System.Windows.Forms.PictureBox pictureBox392
System.Windows.Forms.PictureBox pictureBox393
System.Windows.Forms.PictureBox pictureBox394
System.Windows.Forms.PictureBox pictureBox395
System.Windows.Forms.PictureBox pictureBox396
System.Windows.Forms.PictureBox pictureBox397
System.Windows.Forms.PictureBox pictureBox398
System.Windows.Forms.PictureBox pictureBox399
System.Windows.Forms.PictureBox pictureBox400
System.Windows.Forms.PictureBox pictureBox361
System.Windows.Forms.PictureBox pictureBox362
System.Windows.Forms.PictureBox pictureBox363
System.Windows.Forms.PictureBox pictureBox364
System.Windows.Forms.PictureBox pictureBox365
System.Windows.Forms.PictureBox pictureBox366
System.Windows.Forms.PictureBox pictureBox367
System.Windows.Forms.PictureBox pictureBox368
System.Windows.Forms.PictureBox pictureBox369
System.Windows.Forms.PictureBox pictureBox370
System.Windows.Forms.PictureBox pictureBox371
System.Windows.Forms.PictureBox pictureBox372
System.Windows.Forms.PictureBox pictureBox373
System.Windows.Forms.PictureBox pictureBox374
System.Windows.Forms.PictureBox pictureBox375
System.Windows.Forms.PictureBox pictureBox376
System.Windows.Forms.PictureBox pictureBox377
System.Windows.Forms.PictureBox pictureBox378
System.Windows.Forms.PictureBox pictureBox379
System.Windows.Forms.PictureBox pictureBox380
System.Windows.Forms.PictureBox pictureBox341
System.Windows.Forms.PictureBox pictureBox342
System.Windows.Forms.PictureBox pictureBox343
System.Windows.Forms.PictureBox pictureBox344
System.Windows.Forms.PictureBox pictureBox345
System.Windows.Forms.PictureBox pictureBox346
System.Windows.Forms.PictureBox pictureBox347
System.Windows.Forms.PictureBox pictureBox348
System.Windows.Forms.PictureBox pictureBox349
System.Windows.Forms.PictureBox pictureBox350
System.Windows.Forms.PictureBox pictureBox351
System.Windows.Forms.PictureBox pictureBox352
System.Windows.Forms.PictureBox pictureBox353
System.Windows.Forms.PictureBox pictureBox354
System.Windows.Forms.PictureBox pictureBox355
System.Windows.Forms.PictureBox pictureBox356
System.Windows.Forms.PictureBox pictureBox357
System.Windows.Forms.PictureBox pictureBox358
System.Windows.Forms.PictureBox pictureBox359
System.Windows.Forms.PictureBox pictureBox360
System.Windows.Forms.PictureBox pictureBox321
System.Windows.Forms.PictureBox pictureBox322
System.Windows.Forms.PictureBox pictureBox323
System.Windows.Forms.PictureBox pictureBox324
System.Windows.Forms.PictureBox pictureBox325
System.Windows.Forms.PictureBox pictureBox326
System.Windows.Forms.PictureBox pictureBox327
System.Windows.Forms.PictureBox pictureBox328
System.Windows.Forms.PictureBox pictureBox329
System.Windows.Forms.PictureBox pictureBox330
System.Windows.Forms.PictureBox pictureBox331
System.Windows.Forms.PictureBox pictureBox332
System.Windows.Forms.PictureBox pictureBox333
System.Windows.Forms.PictureBox pictureBox334
System.Windows.Forms.PictureBox pictureBox335
System.Windows.Forms.PictureBox pictureBox336
System.Windows.Forms.PictureBox pictureBox337
System.Windows.Forms.PictureBox pictureBox338
System.Windows.Forms.PictureBox pictureBox339
System.Windows.Forms.PictureBox pictureBox340
System.Windows.Forms.PictureBox pictureBox301
System.Windows.Forms.PictureBox pictureBox302
System.Windows.Forms.PictureBox pictureBox303
System.Windows.Forms.PictureBox pictureBox304
System.Windows.Forms.PictureBox pictureBox305
System.Windows.Forms.PictureBox pictureBox306
System.Windows.Forms.PictureBox pictureBox307
System.Windows.Forms.PictureBox pictureBox308
System.Windows.Forms.PictureBox pictureBox309
System.Windows.Forms.PictureBox pictureBox310
System.Windows.Forms.PictureBox pictureBox311
System.Windows.Forms.PictureBox pictureBox312
System.Windows.Forms.PictureBox pictureBox313
System.Windows.Forms.PictureBox pictureBox314
System.Windows.Forms.PictureBox pictureBox315
System.Windows.Forms.PictureBox pictureBox316
System.Windows.Forms.PictureBox pictureBox317
System.Windows.Forms.PictureBox pictureBox318
System.Windows.Forms.PictureBox pictureBox319
System.Windows.Forms.PictureBox pictureBox320
System.Windows.Forms.PictureBox pictureBox281
System.Windows.Forms.PictureBox pictureBox282
System.Windows.Forms.PictureBox pictureBox283
System.Windows.Forms.PictureBox pictureBox284
System.Windows.Forms.PictureBox pictureBox285
System.Windows.Forms.PictureBox pictureBox286
System.Windows.Forms.PictureBox pictureBox287
System.Windows.Forms.PictureBox pictureBox288
System.Windows.Forms.PictureBox pictureBox289
System.Windows.Forms.PictureBox pictureBox290
System.Windows.Forms.PictureBox pictureBox291
System.Windows.Forms.PictureBox pictureBox292
System.Windows.Forms.PictureBox pictureBox293
System.Windows.Forms.PictureBox pictureBox294
System.Windows.Forms.PictureBox pictureBox295
System.Windows.Forms.PictureBox pictureBox296
System.Windows.Forms.PictureBox pictureBox297
System.Windows.Forms.PictureBox pictureBox298
System.Windows.Forms.PictureBox pictureBox299
System.Windows.Forms.PictureBox pictureBox300
System.Windows.Forms.PictureBox pictureBox261
System.Windows.Forms.PictureBox pictureBox262
System.Windows.Forms.PictureBox pictureBox263
System.Windows.Forms.PictureBox pictureBox264
System.Windows.Forms.PictureBox pictureBox265
System.Windows.Forms.PictureBox pictureBox266
System.Windows.Forms.PictureBox pictureBox267
System.Windows.Forms.PictureBox pictureBox268
System.Windows.Forms.PictureBox pictureBox269
System.Windows.Forms.PictureBox pictureBox270
System.Windows.Forms.PictureBox pictureBox271
System.Windows.Forms.PictureBox pictureBox272
System.Windows.Forms.PictureBox pictureBox273
System.Windows.Forms.PictureBox pictureBox274
System.Windows.Forms.PictureBox pictureBox275
System.Windows.Forms.PictureBox pictureBox276
System.Windows.Forms.PictureBox pictureBox277
System.Windows.Forms.PictureBox pictureBox278
System.Windows.Forms.PictureBox pictureBox279
System.Windows.Forms.PictureBox pictureBox280
System.Windows.Forms.PictureBox pictureBox241
System.Windows.Forms.PictureBox pictureBox242
System.Windows.Forms.PictureBox pictureBox243
System.Windows.Forms.PictureBox pictureBox244
System.Windows.Forms.PictureBox pictureBox245
System.Windows.Forms.PictureBox pictureBox246
System.Windows.Forms.PictureBox pictureBox247
System.Windows.Forms.PictureBox pictureBox248
System.Windows.Forms.PictureBox pictureBox249
System.Windows.Forms.PictureBox pictureBox250
System.Windows.Forms.PictureBox pictureBox251
System.Windows.Forms.PictureBox pictureBox252
System.Windows.Forms.PictureBox pictureBox253
System.Windows.Forms.PictureBox pictureBox254
System.Windows.Forms.PictureBox pictureBox255
System.Windows.Forms.PictureBox pictureBox256
System.Windows.Forms.PictureBox pictureBox257
System.Windows.Forms.PictureBox pictureBox258
System.Windows.Forms.PictureBox pictureBox259
System.Windows.Forms.PictureBox pictureBox260
System.Windows.Forms.PictureBox pictureBox221
System.Windows.Forms.PictureBox pictureBox222
System.Windows.Forms.PictureBox pictureBox223
System.Windows.Forms.PictureBox pictureBox224
System.Windows.Forms.PictureBox pictureBox225
System.Windows.Forms.PictureBox pictureBox226
System.Windows.Forms.PictureBox pictureBox227
System.Windows.Forms.PictureBox pictureBox228
System.Windows.Forms.PictureBox pictureBox229
System.Windows.Forms.PictureBox pictureBox230
System.Windows.Forms.PictureBox pictureBox231
System.Windows.Forms.PictureBox pictureBox232
System.Windows.Forms.PictureBox pictureBox233
System.Windows.Forms.PictureBox pictureBox234
System.Windows.Forms.PictureBox pictureBox235
System.Windows.Forms.PictureBox pictureBox236
System.Windows.Forms.PictureBox pictureBox237
System.Windows.Forms.PictureBox pictureBox238
System.Windows.Forms.PictureBox pictureBox239
System.Windows.Forms.PictureBox pictureBox240
System.Windows.Forms.PictureBox pictureBox201
System.Windows.Forms.PictureBox pictureBox202
System.Windows.Forms.PictureBox pictureBox203
System.Windows.Forms.PictureBox pictureBox204
System.Windows.Forms.PictureBox pictureBox205
System.Windows.Forms.PictureBox pictureBox206
System.Windows.Forms.PictureBox pictureBox207
System.Windows.Forms.PictureBox pictureBox208
System.Windows.Forms.PictureBox pictureBox209
System.Windows.Forms.PictureBox pictureBox210
System.Windows.Forms.PictureBox pictureBox211
System.Windows.Forms.PictureBox pictureBox212
System.Windows.Forms.PictureBox pictureBox213
System.Windows.Forms.PictureBox pictureBox214
System.Windows.Forms.PictureBox pictureBox215
System.Windows.Forms.PictureBox pictureBox216
System.Windows.Forms.PictureBox pictureBox217
System.Windows.Forms.PictureBox pictureBox218
System.Windows.Forms.PictureBox pictureBox219
System.Windows.Forms.PictureBox pictureBox220
System.Windows.Forms.PictureBox pictureBox181
System.Windows.Forms.PictureBox pictureBox182
System.Windows.Forms.PictureBox pictureBox183
System.Windows.Forms.PictureBox pictureBox184
System.Windows.Forms.PictureBox pictureBox185
System.Windows.Forms.PictureBox pictureBox186
System.Windows.Forms.PictureBox pictureBox187
System.Windows.Forms.PictureBox pictureBox188
System.Windows.Forms.PictureBox pictureBox189
System.Windows.Forms.PictureBox pictureBox190
System.Windows.Forms.PictureBox pictureBox191
System.Windows.Forms.PictureBox pictureBox192
System.Windows.Forms.PictureBox pictureBox193
System.Windows.Forms.PictureBox pictureBox194
System.Windows.Forms.PictureBox pictureBox195
System.Windows.Forms.PictureBox pictureBox196
System.Windows.Forms.PictureBox pictureBox197
System.Windows.Forms.PictureBox pictureBox198
System.Windows.Forms.PictureBox pictureBox199
System.Windows.Forms.PictureBox pictureBox200
System.Windows.Forms.PictureBox pictureBox161
System.Windows.Forms.PictureBox pictureBox162
System.Windows.Forms.PictureBox pictureBox163
System.Windows.Forms.PictureBox pictureBox164
System.Windows.Forms.PictureBox pictureBox165
System.Windows.Forms.PictureBox pictureBox166
System.Windows.Forms.PictureBox pictureBox167
System.Windows.Forms.PictureBox pictureBox168
System.Windows.Forms.PictureBox pictureBox169
System.Windows.Forms.PictureBox pictureBox170
System.Windows.Forms.PictureBox pictureBox171
System.Windows.Forms.PictureBox pictureBox172
System.Windows.Forms.PictureBox pictureBox173
System.Windows.Forms.PictureBox pictureBox174
System.Windows.Forms.PictureBox pictureBox175
System.Windows.Forms.PictureBox pictureBox176
System.Windows.Forms.PictureBox pictureBox177
System.Windows.Forms.PictureBox pictureBox178
System.Windows.Forms.PictureBox pictureBox179
System.Windows.Forms.PictureBox pictureBox180
System.Windows.Forms.PictureBox pictureBox141
System.Windows.Forms.PictureBox pictureBox142
System.Windows.Forms.PictureBox pictureBox143
System.Windows.Forms.PictureBox pictureBox144
System.Windows.Forms.PictureBox pictureBox145
System.Windows.Forms.PictureBox pictureBox146
System.Windows.Forms.PictureBox pictureBox147
System.Windows.Forms.PictureBox pictureBox148
System.Windows.Forms.PictureBox pictureBox149
System.Windows.Forms.PictureBox pictureBox150
System.Windows.Forms.PictureBox pictureBox151
System.Windows.Forms.PictureBox pictureBox152
System.Windows.Forms.PictureBox pictureBox153
System.Windows.Forms.PictureBox pictureBox154
System.Windows.Forms.PictureBox pictureBox155
System.Windows.Forms.PictureBox pictureBox156
System.Windows.Forms.PictureBox pictureBox157
System.Windows.Forms.PictureBox pictureBox158
System.Windows.Forms.PictureBox pictureBox159
System.Windows.Forms.PictureBox pictureBox160
System.Windows.Forms.PictureBox pictureBox121
System.Windows.Forms.PictureBox pictureBox122
System.Windows.Forms.PictureBox pictureBox123
System.Windows.Forms.PictureBox pictureBox124
System.Windows.Forms.PictureBox pictureBox125
System.Windows.Forms.PictureBox pictureBox126
System.Windows.Forms.PictureBox pictureBox127
System.Windows.Forms.PictureBox pictureBox128
System.Windows.Forms.PictureBox pictureBox129
System.Windows.Forms.PictureBox pictureBox130
System.Windows.Forms.PictureBox pictureBox131
System.Windows.Forms.PictureBox pictureBox132
System.Windows.Forms.PictureBox pictureBox133
System.Windows.Forms.PictureBox pictureBox134
System.Windows.Forms.PictureBox pictureBox135
System.Windows.Forms.PictureBox pictureBox136
System.Windows.Forms.PictureBox pictureBox137
System.Windows.Forms.PictureBox pictureBox138
System.Windows.Forms.PictureBox pictureBox139
System.Windows.Forms.PictureBox pictureBox140
System.Windows.Forms.PictureBox pictureBox101
System.Windows.Forms.PictureBox pictureBox102
System.Windows.Forms.PictureBox pictureBox103
System.Windows.Forms.PictureBox pictureBox104
System.Windows.Forms.PictureBox pictureBox105
System.Windows.Forms.PictureBox pictureBox106
System.Windows.Forms.PictureBox pictureBox107
System.Windows.Forms.PictureBox pictureBox108
System.Windows.Forms.PictureBox pictureBox109
System.Windows.Forms.PictureBox pictureBox110
System.Windows.Forms.PictureBox pictureBox111
System.Windows.Forms.PictureBox pictureBox112
System.Windows.Forms.PictureBox pictureBox113
System.Windows.Forms.PictureBox pictureBox114
System.Windows.Forms.PictureBox pictureBox115
System.Windows.Forms.PictureBox pictureBox116
System.Windows.Forms.PictureBox pictureBox117
System.Windows.Forms.PictureBox pictureBox118
System.Windows.Forms.PictureBox pictureBox119
System.Windows.Forms.PictureBox pictureBox120
System.Windows.Forms.PictureBox pictureBox81
System.Windows.Forms.PictureBox pictureBox82
System.Windows.Forms.PictureBox pictureBox83
System.Windows.Forms.PictureBox pictureBox84
System.Windows.Forms.PictureBox pictureBox85
System.Windows.Forms.PictureBox pictureBox86
System.Windows.Forms.PictureBox pictureBox87
System.Windows.Forms.PictureBox pictureBox88
System.Windows.Forms.PictureBox pictureBox89
System.Windows.Forms.PictureBox pictureBox90
System.Windows.Forms.PictureBox pictureBox91
System.Windows.Forms.PictureBox pictureBox92
System.Windows.Forms.PictureBox pictureBox93
System.Windows.Forms.PictureBox pictureBox94
System.Windows.Forms.PictureBox pictureBox95
System.Windows.Forms.PictureBox pictureBox96
System.Windows.Forms.PictureBox pictureBox97
System.Windows.Forms.PictureBox pictureBox98
System.Windows.Forms.PictureBox pictureBox99
System.Windows.Forms.PictureBox pictureBox100
System.Windows.Forms.PictureBox pictureBox61
System.Windows.Forms.PictureBox pictureBox62
System.Windows.Forms.PictureBox pictureBox63
System.Windows.Forms.PictureBox pictureBox64
System.Windows.Forms.PictureBox pictureBox65
System.Windows.Forms.PictureBox pictureBox66
System.Windows.Forms.PictureBox pictureBox67
System.Windows.Forms.PictureBox pictureBox68
System.Windows.Forms.PictureBox pictureBox69
System.Windows.Forms.PictureBox pictureBox70
System.Windows.Forms.PictureBox pictureBox71
System.Windows.Forms.PictureBox pictureBox72
System.Windows.Forms.PictureBox pictureBox73
System.Windows.Forms.PictureBox pictureBox74
System.Windows.Forms.PictureBox pictureBox75
System.Windows.Forms.PictureBox pictureBox76
System.Windows.Forms.PictureBox pictureBox77
System.Windows.Forms.PictureBox pictureBox78
System.Windows.Forms.PictureBox pictureBox79
System.Windows.Forms.PictureBox pictureBox80
System.Windows.Forms.PictureBox pictureBox41
System.Windows.Forms.PictureBox pictureBox42
System.Windows.Forms.PictureBox pictureBox43
System.Windows.Forms.PictureBox pictureBox44
System.Windows.Forms.PictureBox pictureBox45
System.Windows.Forms.PictureBox pictureBox46
System.Windows.Forms.PictureBox pictureBox47
System.Windows.Forms.PictureBox pictureBox48
System.Windows.Forms.PictureBox pictureBox49
System.Windows.Forms.PictureBox pictureBox50
System.Windows.Forms.PictureBox pictureBox51
System.Windows.Forms.PictureBox pictureBox52
System.Windows.Forms.PictureBox pictureBox53
System.Windows.Forms.PictureBox pictureBox54
System.Windows.Forms.PictureBox pictureBox55
System.Windows.Forms.PictureBox pictureBox56
System.Windows.Forms.PictureBox pictureBox57
System.Windows.Forms.PictureBox pictureBox58
System.Windows.Forms.PictureBox pictureBox59
System.Windows.Forms.PictureBox pictureBox60
System.Windows.Forms.PictureBox pictureBox21
System.Windows.Forms.PictureBox pictureBox22
System.Windows.Forms.PictureBox pictureBox23
System.Windows.Forms.PictureBox pictureBox24
System.Windows.Forms.PictureBox pictureBox25
System.Windows.Forms.PictureBox pictureBox26
System.Windows.Forms.PictureBox pictureBox27
System.Windows.Forms.PictureBox pictureBox28
System.Windows.Forms.PictureBox pictureBox29
System.Windows.Forms.PictureBox pictureBox30
System.Windows.Forms.PictureBox pictureBox31
System.Windows.Forms.PictureBox pictureBox32
System.Windows.Forms.PictureBox pictureBox33
System.Windows.Forms.PictureBox pictureBox34
System.Windows.Forms.PictureBox pictureBox35
System.Windows.Forms.PictureBox pictureBox36
System.Windows.Forms.PictureBox pictureBox37
System.Windows.Forms.PictureBox pictureBox38
System.Windows.Forms.PictureBox pictureBox39
System.Windows.Forms.PictureBox pictureBox40
System.Windows.Forms.PictureBox pictureBox20
System.Windows.Forms.PictureBox pictureBox19
System.Windows.Forms.PictureBox pictureBox18
System.Windows.Forms.PictureBox pictureBox17
System.Windows.Forms.PictureBox pictureBox16
System.Windows.Forms.PictureBox pictureBox15
System.Windows.Forms.PictureBox pictureBox14
System.Windows.Forms.PictureBox pictureBox13
System.Windows.Forms.PictureBox pictureBox12
System.Windows.Forms.PictureBox pictureBox11
System.Windows.Forms.PictureBox pictureBox10
System.Windows.Forms.PictureBox pictureBox9
System.Windows.Forms.PictureBox pictureBox8
System.Windows.Forms.PictureBox pictureBox7
System.Windows.Forms.PictureBox pictureBox6
System.Windows.Forms.PictureBox pictureBox5
System.Windows.Forms.PictureBox pictureBox4
System.Windows.Forms.PictureBox pictureBox3
System.Windows.Forms.PictureBox pictureBox2
System.Windows.Forms.PictureBox pictureBox1
System.Windows.Forms.Label label1
System.Windows.Forms.TableLayoutPanel tableLayoutPanel2
System.Windows.Forms.Button button2
System.Windows.Forms.Button button1
System.Windows.Forms.Label label2
Static Private Attributes
static System.Timers.Timer aTimer
タイマー
Detailed Description
Definition at line 40 of file FormMain.cs.
Member Function Documentation
appInit()
void ReversiForm.Reversi.appInit ()
アプリ初期化
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 169 of file FormMain.cs.
Referenced by ReversiForm.Reversi.button1_Click(), ReversiForm.Reversi.button2_Click(), and ReversiForm.Reversi.Reversi_Resize().
button1_Click()
void ReversiForm.Reversi.button1_Click (object sender, EventArgs e) private
リセットクリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 487 of file FormMain.cs.
Referenced by ReversiForm.Reversi.InitializeComponent().
button2_Click()
void ReversiForm.Reversi.button2_Click (object sender, EventArgs e) private
セッティングクリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 504 of file FormMain.cs.
Referenced by ReversiForm.Reversi.InitializeComponent().
CurColMsg()
void ReversiForm.Reversi.CurColMsg (string text)
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 410 of file FormMain.cs.
CurColMsgLocal()
void ReversiForm.Reversi.CurColMsgLocal (string text)
現在の色メッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 424 of file FormMain.cs.
Referenced by ReversiForm.Reversi.CurColMsg().
CurStsMsg()
void ReversiForm.Reversi.CurStsMsg (string text)
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 438 of file FormMain.cs.
CurStsMsgLocal()
void ReversiForm.Reversi.CurStsMsgLocal (string text)
現在のステータスメッセージ
Parameters
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 452 of file FormMain.cs.
Referenced by ReversiForm.Reversi.CurStsMsg().
Dispose()
override void ReversiForm.Reversi.Dispose (bool disposing) protected
使用中のリソースをすべてクリーンアップします。
Parameters
disposing マネージ リソースを破棄する場合は true を指定し、その他の場合は false を指定します。
Definition at line 14 of file FormMain.Designer.cs.
DrawSingle()
void ReversiForm.Reversi.DrawSingle (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 283 of file FormMain.cs.
DrawSingleLocal()
void ReversiForm.Reversi.DrawSingleLocal (int y, int x, int sts, int bk, string text)
1マス描画
Parameters
[in] int y Y座標
[in] int x X座標
[in] int sts ステータス
[in] int bk 背景
[in] string text テキスト
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 301 of file FormMain.cs.
Referenced by ReversiForm.Reversi.DrawSingle().
InitializeComponent()
void ReversiForm.Reversi.InitializeComponent () private
デザイナー サポートに必要なメソッドです。このメソッドの内容を コード エディターで変更しないでください。
Definition at line 29 of file FormMain.Designer.cs.
LoadSettingXml()
ReversiSetting ReversiForm.Reversi.LoadSettingXml (string path)
設定XMLファイルロード
Parameters
[in] string path 設定XMLファイルパス
Returns
ReversiSettingオブジェクトインスタンス
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 103 of file FormMain.cs.
OnTimedEvent()
void ReversiForm.Reversi.OnTimedEvent (object source, ElapsedEventArgs e) private
タイマーイベント
Parameters
[in] object source
[in] ElapsedEventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 592 of file FormMain.cs.
Referenced by ReversiForm.Reversi.Reversi_Resize().
pictureBox_Click()
void ReversiForm.Reversi.pictureBox_Click (object sender, EventArgs e) private
マスクリック
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 467 of file FormMain.cs.
Referenced by ReversiForm.Reversi.InitializeComponent().
Reversi_Resize()
void ReversiForm.Reversi.Reversi_Resize (object sender, EventArgs e) private
リサイズイベント
リサイズ終了イベント
Parameters
[in] object sender
[in] EventArgs e
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 534 of file FormMain.cs.
Referenced by ReversiForm.Reversi.InitializeComponent().
SaveSettingXml()
int ReversiForm.Reversi.SaveSettingXml (string path, ref ReversiSetting appSet)
設定XMLファイルセーブ
Parameters
[in] string path 設定XMLファイルパス
[out] ReversiSetting appSet 設定XMLファイルオブジェクト
Returns
0 : 成功 それ以外 : 失敗
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 137 of file FormMain.cs.
Referenced by ReversiForm.Reversi.button2_Click().
ViewMsgDlg()
void ReversiForm.Reversi.ViewMsgDlg (string title, string msg)
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 250 of file FormMain.cs.
ViewMsgDlgLocal()
void ReversiForm.Reversi.ViewMsgDlgLocal (string title, string msg)
メッセージダイアログ
Parameters
[in] string title タイトル
[in] string msg メッセージ
Returns
ありません
Author
Yuta Yoshinaga
Date
2017.10.20
Definition at line 265 of file FormMain.cs.
Referenced by ReversiForm.Reversi.ViewMsgDlg().
Member Data Documentation
components
System.ComponentModel.IContainer ReversiForm.Reversi.components = null private
必要なデザイナー変数です。
Definition at line 8 of file FormMain.Designer.cs.
Referenced by ReversiForm.Reversi.Dispose().
The documentation for this class was generated from the following files:
FormMain.cs
FormMain.Designer.cs